name: "FRP Client"
description: "You can use this tool to achieve remote access to local Home Assistant OS by port forwarding"
version: "1.0.1"
slug: "frp_client"
host_network: true
startup: application
boot: "auto"
init: false
map:
  - "share:rw"
privileged:
  - NET_ADMIN
devices:
  - /dev/net/tun
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serverAddr: "vip.slzn999.tk"
  serverPort: 17010
  user: "user1"
  metadatas.token: "123456789"
  subDomain: "example"
  proxyName: "homeassistant"
schema:
  serverAddr: str
  serverPort: int
  user: str
  metadatas.token: str
  subDomain: str
  proxyName: str
