serverAddr = "example.com"
serverPort = 7000
user = "user1"
metadatas.token = "123456789"

log.level = "info"
log.to = "/share/frpc.log"
log.maxDays = 3

[[proxies]]
name = "homeassistant"
type = "http"
subdomain = "example"
localIP = "127.0.0.1"
localPort = 8123
transport.useEncryption = true
transport.useCompression = true

[[proxies]]
name = "ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
transport.useEncryption = true
transport.useCompression = true


# [proxies.plugin]
# type = "https2http"
# localAddr = "your_ip:8123"
# crtPath = "/share/frp/fullchain.pem"
# keyPath = "/share/frp/privkey.pem"
# hostHeaderRewrite = "your_host_header_rewrite"
# requestHeaders.set.x-from-where = "frp"

